#!/bin/sh 
# vim:fileencoding=utf-8:foldmethod=marker

# This is configuration file for river.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.
 
# Variables {{{

# River directory
dir=$HOME/.config/river

# Imports
volume="$dir/scripts/volume.sh"
waylock="$dir/scripts/waylock.sh"
downloader="$dir/scripts/bemenu_downloader.sh"
colorpicker="$dir/scripts/colorpicker.sh"
screenshot="$dir/scripts/screenshot.sh"
screenshoter="$dir/scripts/bemenu_screenshoter.sh"
networkmanager="$dir/scripts/networkmanager.py"

# Options
bemenu_opts="-c -i -l 10 --fn 'JetBrainsMono Nerd Font 16' -B 2 -M 670 -s --fixed-height --binding vim --vim-normal-mode --vim-esc-exits --tb '#81A1C1' --tf '#2E3440' --fb '#2E3440' --ff '#D8DEE9' --nb '#2E3440' --nf '#D8DEE9' --ab '#2E3440' --af '#D8DEE9' --hb '#81A1C1' --hf '#2E3440' --sb '#434C5E' --sf '#B48EAD' --scb '#2E3440' --scf '#D8DEE9' --cb '#434C5E' --cf '#D8DEE9' --bdr '#81A1C1'"

# }}}
# Autostart {{{

# Launch autostart.sh
riverctl spawn "$dir/scripts/autostart.sh"

# }}}
# Keyboard keybindings {{{

# Super + Shift + Return to start an instance of foot
riverctl map -layout 0 normal Super Return spawn footclient

# Super + T to start an instance of floating foot
riverctl map -layout 0 normal Super T spawn "footclient --app-id 'footclient-float' --window-size-pixels 1000x600"

# Super+C to close the focused view
riverctl map -layout 0 normal Super C close

# Control + Alt + L to lock screen
riverctl map -layout 0 normal Control+Alt L spawn $waylock 

# Super + Shift + R to reload river configuration
riverctl map -layout 0 normal Super+Shift R spawn "$dir/init"

# Super+Shift+Q to exit river
riverctl map -layout 0 normal Super+Shift Q exit

# Focus previous tags
riverctl map -layout 0 normal Alt Tab focus-previous-tags

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map -layout 0 normal Super J focus-view next
riverctl map -layout 0 normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map -layout 0 normal Super+Shift J swap next
riverctl map -layout 0 normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map -layout 0 normal Super Period focus-output next
riverctl map -layout 0 normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map -layout 0 normal Super+Shift Period send-to-output next
riverctl map -layout 0 normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map -layout 0 normal Super+Shift Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map -layout 0 normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map -layout 0 normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map -layout 0 normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map -layout 0 normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map -layout 0 normal Super+Alt H move left 100
riverctl map -layout 0 normal Super+Alt J move down 100
riverctl map -layout 0 normal Super+Alt K move up 100
riverctl map -layout 0 normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map -layout 0 normal Super+Alt+Control H snap left
riverctl map -layout 0 normal Super+Alt+Control J snap down
riverctl map -layout 0 normal Super+Alt+Control K snap up
riverctl map -layout 0 normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map -layout 0 normal Super+Alt+Shift H resize horizontal -100
riverctl map -layout 0 normal Super+Alt+Shift J resize vertical 100
riverctl map -layout 0 normal Super+Alt+Shift K resize vertical -100
riverctl map -layout 0 normal Super+Alt+Shift L resize horizontal 100
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map -layout 0 normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map -layout 0 normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map -layout 0 normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map -layout 0 normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map -layout 0 normal Super 0 set-focused-tags $all_tags
riverctl map -layout 0 normal Super+Shift 0 set-view-tags $all_tags

# The scratchpad will live on an unused tag. Which tags are used depends on your
# config, but rivers default uses the first 9 tags.
scratch_tag=$((1 << 9 ))

# Toggle the scratchpad with Super+P
riverctl map -layout 0 normal Super P toggle-focused-tags ${scratch_tag}

# Send windows to the scratchpad with Super+Shift+P
riverctl map -layout 0 normal Super+Shift P set-view-tags ${scratch_tag}

# Set spawn tagmask to ensure new windows don't have the scratchpad tag unless
# explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}

# Super+Space to toggle float
riverctl map -layout 0 normal Super Z toggle-float

# Super+F to toggle fullscreen
riverctl map -layout 0 normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map -layout 0 normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map -layout 0 normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map -layout 0 normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map -layout 0 normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping -layout 0 to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map -layout 0 normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map -layout 0 passthrough Super F11 enter-mode normal

# Various media key mapping -layout 0 examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    riverctl map -layout 0 $mode None XF86HomePage    spawn firefox
    riverctl map -layout 0 $mode None XF86Explorer    spawn nemo
    riverctl map -layout 0 $mode None XF86Mail        spawn thunderbird
    riverctl map -layout 0 $mode None XF86Tools       spawn "footclient --app-id 'footclient-float' --window-size-pixels 800x400 ncmpcpp -s visualizer -S playlist"
    riverctl map -layout 0 $mode None XF86Calculator  spawn galculator

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map -layout 0 $mode None XF86AudioRaiseVolume  spawn "$volume --inc"
    riverctl map -layout 0 $mode None XF86AudioLowerVolume  spawn "$volume --dec"
    riverctl map -layout 0 $mode None XF86AudioMute         spawn "$volume --toggle"

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map -layout 0 $mode None XF86AudioNext  spawn 'playerctl next'
    riverctl map -layout 0 $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map -layout 0 $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map -layout 0 $mode None XF86AudioStop  spawn 'playerctl stop'
done

### Colorpicker -------------------------------------------
# Alt + P to pick color
riverctl map -layout 0 normal Alt P spawn "$colorpicker"

### Screenshot --------------------------------------------
# Print to take screenshot
riverctl map -layout 0 normal None Print    spawn "$screenshot --now"

# Control + Print to take screenshot in 5 seconds
riverctl map -layout 0 normal Control Print spawn "$screenshot --in5"

# Shift + Print to take screenshot in 10 seconds
riverctl map -layout 0 normal Shift Print   spawn "$screenshot --in10"

# Super + Print to take screenshot of selected area
riverctl map -layout 0 normal Super Print   spawn "$screenshot --area"

### Bemenu applets ----------------------------------------
# Alt + F1 to open the app launcher applet
riverctl map -layout 0 normal Alt F1  spawn "j4-dmenu-desktop --dmenu=\"LD_LIBRARY_PATH=/usr/local/lib bemenu -p Apps --fixed-height $bemenu_opts\""

# Super + R to open the app runner applet
riverctl map -layout 0 normal Super R spawn "LD_LIBRARY_PATH=/usr/local/lib bemenu-run -p \"󰜎\" --fixed-height $bemenu_opts"

# Super + N to open the network manager applet
riverctl map -layout 0 normal Super N spawn $networkmanager

# Super + D to open the downloader applet
riverctl map -layout 0 normal Super D spawn $downloader

# Super + S to open the screenshoter applet
riverctl map -layout 0 normal Super S spawn $screenshoter

# }}}
# Mouse keybindings {{{

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# }}}
# Mouse/Keyboard options {{{

# Keyboard layout (xkblayout)
riverctl keyboard-layout -model pc105 -variant qwerty -options "grp:win_space_toggle" "us,ru"

# Set keyboard repeat rate
riverctl set-repeat 25 300

# Fix mouse sensitivity
riverctl input pointer-1133-49298-Logitech_G102_LIGHTSYNC_Gaming_Mouse pointer-accel -1.0

# Focus follows cursor
riverctl focus-follows-cursor normal

# }}}
# Layout {{{

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

# }}}
# Float {{{

declare -a float_apps=(
    "*float*"
    "galculator"
)

for float_app in "${float_apps[@]}"; do
    riverctl rule-add -app-id "$float_app" float
done

# }}}
# River colors {{{

# Set background and border color
riverctl background-color 0x2E3440
riverctl border-color-focused 0x81A1C1
riverctl border-color-unfocused 0x3B4252
riverctl border-color-urgent 0xA3BE8C

# }}}
# Server Side Decorations (SSD) {{{

declare -a ssd_apps=(
    "firefox"
    "piper"
    "steam"
    "nemo"
    "mpv"
    "avahi*"
    "*Meld*"
    "lutris"
    "Waydroid"
    "galculator"
    "*telegram*"
    "*pavucontrol*"
)

for ssd_app in "${ssd_apps[@]}"; do
    riverctl rule-add -app-id "$ssd_app" ssd
done

# }}}
